### ISSUE TITLE
Request for additional changes

### ISSUE THREAD

**Issue by palaparthi** [nodu/teamster#2]
Thanks for dockerizing the project, I was able to get it to work. I have few change requests
1. Server side validations are missing. For example phone number, can you please add them with tests?
2. Can you add pagination for the list view.

**Comment by nodu** [comment]
Heya @palaparthi , Glad you were able to get the project running via Docker. 

1. I've added additional validations and aligned these with the UI.
2. To help with your pagination testing, I've added a Seed button at the top of the initial UI view. 

I've pushed up new images, so you should just have to pull and run them again:

```shell
docker pull nodu/teamster:ui
docker pull nodu/teamster:api

docker run --rm -p 8000:8000 nodu/teamster:api
docker run --rm -p 80:3000 nodu/teamster:ui
```

**Comment by palaparthi** [comment]
Thanks for adding the pagination, the validations still doesn't seem to be working as expected. I am able to add a user with the same phone number, see below.

![Screenshot 2024-10-25 at 12 28 23 PM](https://github.com/user-attachments/assets/eab90c57-246b-40b1-a1c1-b0770aeed902)

**Comment by nodu** [comment]
@palaparthi Phone numbers are now unique. Give it a go. New images have been pushed.
